version: '3.9'
services:
  kb-service:
    build:
      context: ./kb-service
    container_name: kb-service
    ports:
    - 7001:7001
    environment: {}
  reasoner:
    build:
      context: ./reasoner
    container_name: reasoner
    ports:
    - 7002:7002
    environment:
      KB_URL: http://kb-service:7001
    depends_on:
    - kb-service
  safety-runtime:
    build:
      context: ./safety-runtime
    container_name: safety-runtime
    ports:
    - 7003:7003
    environment:
      UQ_THRESHOLD: '0.55'
  telemetry-agent:
    build:
      context: ./telemetry-agent
    container_name: telemetry-agent
    ports:
    - 7000:7000
    environment:
      KB_URL: http://kb-service:7001
      REASONER_URL: http://reasoner:7002
      SAFETY_URL: http://safety-runtime:7003
    depends_on:
    - kb-service
    - reasoner
    - safety-runtime
  operator-console:
    build:
      context: ./operator-console
    container_name: operator-console
    ports:
    - 9988:9988
    environment:
      TELEMETRY_URL: http://telemetry-agent:7000
      KB_URL: http://kb-service:7001
      REASONER_URL: http://reasoner:7002
      SAFETY_URL: http://safety-runtime:7003
    depends_on:
    - telemetry-agent
    - kb-service
    - reasoner
    - safety-runtime
