version: "3.9"
services:
  neo4j:
    image: neo4j:5.23
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_memory_pagecache_size=512M
      - NEO4J_server_memory_heap_initial__size=512M
      - NEO4J_server_memory_heap_max__size=512M
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  telemetry-agent:
    build: ./telemetry-agent
    image: semantos/telemetry-agent:local
    environment:
      - USE_EBPF=auto
      - SAMPLE_WINDOW=60
    # To enable eBPF, you may need extra privileges and mounts:
    # privileged: true
    # pid: "host"
    # volumes:
    #   - /lib/modules:/lib/modules:ro
    #   - /sys/kernel/debug:/sys/kernel/debug
    ports:
      - "9101:8000"
    depends_on:
      - neo4j

  kb-service:
    build: ./kb-service
    image: semantos/kb-service:local
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=password
      - DATA_DIR=/data
    volumes:
      - kb_data:/data
    ports:
      - "9102:8000"
    depends_on:
      - neo4j

  reasoner:
    build: ./reasoner
    image: semantos/reasoner:local
    environment:
      - KB_URL=http://kb-service:8000
      - TELEMETRY_URL=http://telemetry-agent:8000
      # - OPENAI_API_KEY=sk-...
      # - OPENAI_MODEL=gpt-4o-mini
      # - OLLAMA_HOST=http://host.docker.internal:11434
      # - OLLAMA_MODEL=llama3.1
    ports:
      - "9103:8000"
    depends_on:
      - kb-service
      - telemetry-agent

  safety-runtime:
    build: ./safety-runtime
    image: semantos/safety-runtime:local
    environment:
      - TAU=0.55
      - ROLLOUT_STEPS=5,25,50,100
      - SLO_MAX_P95=35
      - LOG_DIR=/app/outputs
    volumes:
      - ./outputs:/app/outputs
    ports:
      - "9104:8000"
    depends_on:
      - reasoner

  operator-console:
    build: ./operator-console
    image: semantos/operator-console:local
    ports:
      - "9988:9988"
    volumes:
      - ./outputs:/app/outputs
    depends_on:
      - telemetry-agent
      - kb-service
      - reasoner
      - safety-runtime

volumes:
  neo4j_data:
  neo4j_logs:
  kb_data:
