version: '3.8'

services:
  # 1) Knowledge Base (KB) Service
  kb-service:
    build:
      context: .
      dockerfile: kb-service/Dockerfile
    container_name: kb-service
    restart: unless-stopped
    ports:
      - "50052:50052"     # gRPC
    volumes:
      - ./data/kb:/app/data

  # 2) Reasoner (LLM 추론)
  reasoner:
    build:
      context: .
      dockerfile: reasoner/Dockerfile
    container_name: reasoner
    restart: unless-stopped
    ports:
      - "50053:50053"     # gRPC
    depends_on:
      - kb-service

  # 3) Safety Runtime (SLO 감시 및 제어)
  safety-runtime:
    build:
      context: .
      dockerfile: safety-runtime/Dockerfile
    container_name: safety-runtime
    restart: unless-stopped
    privileged: true        # eBPF/커널 노브 제어 필요 시
    ports:
      - "50051:50051"       # gRPC
    depends_on:
      - kb-service
      - reasoner

  # 4) Telemetry Agent (eBPF 커널 메트릭 수집)
  telemetry-agent:
    build:
      context: .
      dockerfile: telemetry-agent/Dockerfile
    container_name: telemetry-agent
    restart: unless-stopped
    privileged: true
    pid: "host"             # eBPF에서 전체 PID 접근
    volumes:
      - /sys/kernel/debug:/sys/kernel/debug:ro
      - /lib/modules:/lib/modules:ro
    depends_on:
      - safety-runtime

  # 5) Operator Console (Vue 빌드 → Nginx 정적 서빙, gRPC-Web 프록시)
  operator-console:
    build:
      context: .
      dockerfile: operator-console/Dockerfile
    container_name: operator-console
    restart: unless-stopped
    ports:
      - "9988:8080"         # 로컬 접속: http://localhost:9988/
    depends_on:
      - reasoner
      - kb-service
      - safety-runtime

