version: '3.8'

services:
  kb-service:
    build:
      context: .
      dockerfile: kb-service/Dockerfile
    container_name: kb-service
    ports:
      - "50052:50052"
    volumes:
      - ./data/kb:/app/data
    # networks: [semantos-net]

  reasoner:
    build:
      context: .
      dockerfile: reasoner/Dockerfile
    container_name: reasoner
    ports:
      - "50053:50053"
    depends_on:
      - kb-service
    # networks: [semantos-net]

  safety-runtime:
    build:
      context: .
      dockerfile: safety-runtime/Dockerfile
    container_name: safety-runtime
    privileged: true
    ports:
      - "50051:50051"
    depends_on:
      - kb-service
      - reasoner
    # networks: [semantos-net]

  telemetry-agent:
    build:
      context: .
      dockerfile: telemetry-agent/Dockerfile
    container_name: telemetry-agent
    privileged: true
    pid: "host"
    volumes:
      - /sys/kernel/debug:/sys/kernel/debug:ro
      - /lib/modules:/lib/modules:ro
    depends_on:
      - safety-runtime
    # networks: [semantos-net]

  envoy:
    image: envoyproxy/envoy:v1.31-latest
    container_name: grpc-web-gateway
    command: ["-c", "/etc/envoy/envoy.yaml", "-l", "info"]
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "9900:9900"   # Envoy admin (옵션)
      - "18080:18080" # Envoy HTTP listener (grpc-web 진입점)
    depends_on:
      - reasoner
      - safety-runtime
    # networks: [semantos-net]

  operator-console:
    build:
      context: .
      dockerfile: operator-console/Dockerfile
    container_name: operator-console
    ports:
      - "9988:80"   # UI는 9988
    depends_on:
      - envoy   # 또는 grpc-web-gateway 이름 (당신의 compose 설정에 맞게)
    volumes:
      - ./operator-console/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # networks: [semantos-net]

# networks:
#   semantos-net:
#     driver: bridge

