// @generated by protoc-gen-ts-web. Do not edit!

import * as jspb from 'google-protobuf';

export class TelemetrySnapshot extends jspb.Message {
  getHostId(): string;
  setHostId(value: string): void;

  getMetricsMap(): jspb.Map<string, number>;
  clearMetricsMap(): void;

  getCurrentKnobsMap(): jspb.Map<string, string>;
  clearCurrentKnobsMap(): void;
  
  toObject(includeInstance?: boolean): TelemetrySnapshot.AsObject;
  static toObject(includeInstance: boolean, msg: TelemetrySnapshot): TelemetrySnapshot.AsObject;
  static serializeBinaryToWriter(message: TelemetrySnapshot, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): TelemetrySnapshot;
}

export namespace TelemetrySnapshot {
  export type AsObject = {
    hostId: string;
    metricsMap: Array<[string, number]>;
    currentKnobsMap: Array<[string, string]>;
  }
}

export class TuningRecommendation extends jspb.Message {
  getKnobName(): string;
  setKnobName(value: string): void;

  getProposedValue(): string;
  setProposedValue(value: string): void;

  getRationale(): string; // LLM이 생성한 설명
  setRationale(value: string): void;

  getUncertaintyScore(): number;
  setUncertaintyScore(value: number): void;
  
  getPredictedImpactMap(): jspb.Map<string, number>;
  clearPredictedImpactMap(): void;
  
  toObject(includeInstance?: boolean): TuningRecommendation.AsObject;
  static toObject(includeInstance: boolean, msg: TuningRecommendation): TuningRecommendation.AsObject;
  static serializeBinaryToWriter(message: TuningRecommendation, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): TuningRecommendation;
}

export namespace TuningRecommendation {
  export type AsObject = {
    knobName: string;
    proposedValue: string;
    rationale: string;
    uncertaintyScore: number;
    predictedImpactMap: Array<[string, number]>;
  }
}

// ... ApplyResponse, LogResponse, OptimizationTrace 등 나머지 메시지 정의 ...