FROM ubuntu:22.04

RUN apt-get update && apt-get install -y --no-install-recommends     python3 python3-pip ca-certificates curl     bpfcc-tools python3-bpfcc linux-tools-common kmod  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN python3 -m pip install --no-cache-dir -r /app/requirements.txt

COPY app.py /app/app.py

ENV USE_EBPF=auto
ENV SAMPLE_WINDOW=60

EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
