# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/semantos.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/semantos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/semantos.proto\x12\x08semantos\"\x8a\x02\n\x11TelemetrySnapshot\x12\x0f\n\x07host_id\x18\x01 \x01(\t\x12\x39\n\x07metrics\x18\x02 \x03(\x0b\x32(.semantos.TelemetrySnapshot.MetricsEntry\x12\x44\n\rcurrent_knobs\x18\x03 \x03(\x0b\x32-.semantos.TelemetrySnapshot.CurrentKnobsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1a\x33\n\x11\x43urrentKnobsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xf6\x01\n\x14TuningRecommendation\x12\x11\n\tknob_name\x18\x01 \x01(\t\x12\x16\n\x0eproposed_value\x18\x02 \x01(\t\x12\x11\n\trationale\x18\x03 \x01(\t\x12\x19\n\x11uncertainty_score\x18\x04 \x01(\x01\x12M\n\x10predicted_impact\x18\x05 \x03(\x0b\x32\x33.semantos.TuningRecommendation.PredictedImpactEntry\x1a\x36\n\x14PredictedImpactEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"N\n\rApplyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0estatus_message\x18\x02 \x01(\t\x12\x14\n\x0c\x61udit_log_id\x18\x03 \x01(\t\"\xc2\x01\n\x11OptimizationTrace\x12\x32\n\rinitial_state\x18\x01 \x01(\x0b\x32\x1b.semantos.TelemetrySnapshot\x12.\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\x1e.semantos.TuningRecommendation\x12\x32\n\routcome_state\x18\x03 \x01(\x0b\x32\x1b.semantos.TelemetrySnapshot\x12\x15\n\rslo_violation\x18\x04 \x01(\x08\"S\n\x18TuningRecommendationList\x12\x37\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x1e.semantos.TuningRecommendation\"\x1e\n\x0bLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xf9\x01\n\x0fSemantosControl\x12U\n\x12GetRecommendations\x12\x1b.semantos.TelemetrySnapshot\x1a\".semantos.TuningRecommendationList\x12M\n\x12\x41pplyConfiguration\x12\x1e.semantos.TuningRecommendation\x1a\x17.semantos.ApplyResponse\x12@\n\nLogOutcome\x12\x1b.semantos.OptimizationTrace\x1a\x15.semantos.LogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.semantos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYSNAPSHOT_METRICSENTRY']._loaded_options = None
  _globals['_TELEMETRYSNAPSHOT_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_TELEMETRYSNAPSHOT_CURRENTKNOBSENTRY']._loaded_options = None
  _globals['_TELEMETRYSNAPSHOT_CURRENTKNOBSENTRY']._serialized_options = b'8\001'
  _globals['_TUNINGRECOMMENDATION_PREDICTEDIMPACTENTRY']._loaded_options = None
  _globals['_TUNINGRECOMMENDATION_PREDICTEDIMPACTENTRY']._serialized_options = b'8\001'
  _globals['_TELEMETRYSNAPSHOT']._serialized_start=35
  _globals['_TELEMETRYSNAPSHOT']._serialized_end=301
  _globals['_TELEMETRYSNAPSHOT_METRICSENTRY']._serialized_start=202
  _globals['_TELEMETRYSNAPSHOT_METRICSENTRY']._serialized_end=248
  _globals['_TELEMETRYSNAPSHOT_CURRENTKNOBSENTRY']._serialized_start=250
  _globals['_TELEMETRYSNAPSHOT_CURRENTKNOBSENTRY']._serialized_end=301
  _globals['_TUNINGRECOMMENDATION']._serialized_start=304
  _globals['_TUNINGRECOMMENDATION']._serialized_end=550
  _globals['_TUNINGRECOMMENDATION_PREDICTEDIMPACTENTRY']._serialized_start=496
  _globals['_TUNINGRECOMMENDATION_PREDICTEDIMPACTENTRY']._serialized_end=550
  _globals['_APPLYRESPONSE']._serialized_start=552
  _globals['_APPLYRESPONSE']._serialized_end=630
  _globals['_OPTIMIZATIONTRACE']._serialized_start=633
  _globals['_OPTIMIZATIONTRACE']._serialized_end=827
  _globals['_TUNINGRECOMMENDATIONLIST']._serialized_start=829
  _globals['_TUNINGRECOMMENDATIONLIST']._serialized_end=912
  _globals['_LOGRESPONSE']._serialized_start=914
  _globals['_LOGRESPONSE']._serialized_end=944
  _globals['_SEMANTOSCONTROL']._serialized_start=947
  _globals['_SEMANTOSCONTROL']._serialized_end=1196
# @@protoc_insertion_point(module_scope)
