openapi: 3.0.0
info:
  title: SemantOS Control API
  version: "0.1.0"
paths:
  /get_recommendations:
    post:
      summary: Get recommendations from reasoner
      responses:
        "200":
          description: OK
  /apply:
    post:
      summary: Apply a configuration via Safety Runtime
      responses:
        "200":
          description: OK
  /log_outcome:
    post:
      summary: Log optimization outcome to KB
      responses:
        "200":
          description: OK
